name: Push Folder to Another Repository

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  push-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze2402/main_repo.git next_repo
        # Replace 'yourusername' with your GitHub username and 'target-repo' with the name of your target repository

      - name: Create target directory
        run: mkdir -p next_repo/files_new  

      - name: Copy folder to target repository
        run: |
          cp -r files/* next_repo/files_new
          cd next_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.mein_token}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Copy files from source repository"
          git push

