name: Convert and Push to Another Repository

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  convert_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc  # Install Pandoc

      - name: Convert .docx to .md
        run: |
          for file in *.docx; do
              pandoc "$file" -o "${file%.docx}.md"
          done

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "matze2402"

      - name: Clone Another Repository
        uses: actions/checkout@v2
        with:
          repository: matze2402/next_repo
          path: next_repo

      - name: Copy .md Files to Another Repository Folder
        run: |
          mkdir -p next_repo/files_new  # Adjust folder path
          cp *.md next_repo/files_new

      - name: Commit and Push Changes
        working-directory: another_repo
        run: |
          git add .
          git commit -m "Automatic commit from GitHub Actions"
          git push
