name: Convert and Push to Another Repository

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  convert_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc  # Install Pandoc

      - name: Check for .docx files
        run: |
          shopt -s nullglob
          if ! compgen -G "files/*.docx" > /dev/null; then
            echo "No .docx files found"
            exit 0
          fi

      - name: Convert .docx to .md
        run: |
          for file in files/*.docx; do
              pandoc "$file" -o "${file%.docx}.md"
          done

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "matze2402"

      - name: Clone target repository
        run: git clone https://github.com/matze2402/next_repo.git next_repo
        # Replace 'yourusername' with your GitHub username and 'target-repo' with the name of your target repository

      - name: Copy .md files to target repository
        run: |
          mkdir -p next_repo/files_new
          cp files/*.md next_repo/files_new/
          cd next_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git add .
          # Check if there are any .md files to commit
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Copy .md files from source repository"
            git push origin main
          else
            echo "No .md files to commit"
          fi
